### ISSUE TITLE
databases

### ISSUE THREAD

**Issue by Xurshid7777** [BaseMax/iApkWebSystem#1]
hello, please upload .sql databases

**Comment by BaseMax** [comment]
Hi @Xurshid7777,

Do you want know SQL structure?

Best,

**Comment by Xurshid7777** [comment]
yes, all  structure

**Comment by BaseMax** [comment]
Okay, i will upload structure of tables and fields.
Can you introduce yourself? @Xurshid7777

**Comment by Xurshid7777** [comment]
Thanks, My name  is Xurshid

**Comment by BaseMax** [comment]
It may not be a great structure. But it also comes with good performance. Because it contains thousands upon thousands of rows.

https://github.com/BaseMax/iApkWebSystem/blob/master/iapk-structure.sql

**Comment by Xurshid7777** [comment]
you used sql view ??

**Comment by Xurshid7777** [comment]
my telegram sending message https://t.me/xurwidbek

**Comment by BaseMax** [comment]
> you used sql view ??

What do you means?
It's MySQL, Mariadb.

**Comment by Xurshid7777** [comment]
yes
